# Action Name
name: Run Newman as a GitHub Action

# How is this action triggered?
on:
  push: #Trigger when pushed to the main branch
    branches:
    - main
  schedule: #Run on a schedule
  - cron: "0 1 * * 1-5"
  workflow_dispatch: #Trigger manually

# This is the job that will run.
jobs:
  test-api:
    runs-on: ubuntu-latest

    # These are the steps within the job.
    steps: 
    # 1. Checkout Repository
    - name: Checkout Repository
      uses: actions/checkout@v1

    # 2. Run Newman with params
    - name: Run Newman
      id: run-newman
      uses: anthonyvscode/newman-action@v1
      with:
        collection: Newman_2022April18/Collection.json
        iterationData: Newman_2022April18/IterationData.json
        iterationCount: 3 #Does this need to be specified manually?
        reporters: cli
        bail: false
        suppressExitCode: false

    # 3. View Test Results in Console
    - name: Output summary to console
      run: echo ${{ steps.run-newman.outputs.summary_full }} #summary_full is important!
